apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: "{{ .Values.dockerhubName }}/{{ .Values.imageName }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          env:
            - name: K8S_POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: APP_NAME
              value: {{ .Values.name }}
            - name: KAFKA_BROKER_ADDRESS
              value: {{ .Values.kafka.address }}
            - name: KAFKA_TOPIC
              value: {{ .Values.kafka.topic }}
            - name: KAFKA_CONSUMER_GROUP_ID
              value: {{ .Values.kafka.groupId }}
            - name: MYSQL_SERVER
              value: {{ .Values.mysql.server }}
            - name: MYSQL_USERNAME
              value: {{ .Values.mysql.username }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.mysql.password }}
            - name: MYSQL_PORT
              value: "{{ .Values.mysql.port }}"
            - name: MYSQL_DATABASE
              value: {{ .Values.mysql.database }}
            - name: MYSQL_TABLE
              value: {{ .Values.mysql.table }}
            - name: OTEL_SERVICE_NAME
              value: {{ .Values.name }}
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: service.name=$(OTEL_SERVICE_NAME),service.instance.id=$(K8S_POD_NAME)
            - name: OTEL_EXPORTER_TYPE
              value: {{ .Values.otel.exporter }}
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: {{ .Values.otlp.endpoint }}
            - name: OTEL_EXPORTER_OTLP_HEADERS
              value: {{ .Values.otlp.headers }}
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
