apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: "{{ .Values.dockerhubName }}/{{ .Values.imageName }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          env:
            - name: APP_NAME
              value: {{ .Values.name }}
            - name: HTTP_SERVER_REQUEST_INTERVAL
              value: "{{ .Values.httpserver.requestInterval }}"
            - name: HTTP_SERVER_ENDPOINT
              value: {{ .Values.httpserver.endpoint }}
            - name: HTTP_SERVER_PORT
              value: "{{ .Values.httpserver.port }}"
            - name: OTEL_SERVICE_NAME
              value: {{ .Values.name }}
            - name: OTEL_EXPORTER_TYPE
              value: {{ .Values.otel.exporter }}
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: {{ .Values.otlp.endpoint }}
            - name: OTEL_EXPORTER_OTLP_HEADERS
              value: {{ .Values.otlp.headers }}
          ports:
            - protocol: TCP
              containerPort: {{ .Values.port }}
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
